### PR TITLE
Networking fun!

### PR DESCRIPTION
**Pull request by TheGlitch76**
- Drop the packet suffix on packets
- Move packets to a package based on the "game state" as roughly described on wiki.vg
- Map classes involved with the initial player connection handling
- ServerProperties class
- Various other stuff in MinecraftServer

### CODE REVIEW

**Comment by valoeghese** [comment]
Packets should still have the packet suffix imo

**Comment by valoeghese** [comment]
actually, if we have S2C and C2S suffixes then maybe we can drop the packet suffix

**Comment by valoeghese** [comment]
and liach's and Daniel's reviews

**Comment by TheGlitch76** [comment]
what, why did build.gradle change?

**Comment by valoeghese** [comment]
just copy the build.gradle from MCPOmf and paste it into your local clone

**Comment by TheGlitch76** [comment]
Git is confused. I'm not changing the build.gradle from latest, but my fork is based off of an earlier commit

**Pull request closed without merging**
