### PR TITLE
Some mappings. Also Fixes #27

### LINKED ISSUE #27: net.minecraft.world.level.storage package should be net.minecraft.level.storage

### PR DESCRIPTION
**Pull request by valoeghese**

### CODE REVIEW

**Comment by valoeghese** [comment]
@quat1024 @shedaniel @liach review pls

**Comment by shedaniel** [comment]
oh no
Math to Maths

**Comment by quat1024** [comment]
`maths` is pretty spicy tbh, but i guess it makes sense because theres english spelling for everything else lol??

**Comment by shedaniel** [comment]
can’t wait to use MathsHelper.clamp() and Colour.RED

**Comment by valoeghese** [comment]
Yeah. Math -> Maths bc British english

**Pull request merged**
